# 10.6 Exercise: Aggregates

1. Write a summary about each aggregate function mentioned (np.mean, np.std, np.var, np.argmin, np.argmax, np.median, np.percentile).
2. Come up with a small sample of code (with appropriate setup/data) that illustrates the usage of at least four (4) of the aggregate functions (from Part 1). Include the results/output as well.
3. Find a sample data set (or create a reasonable data set and place in an appropriate structure, e.g., DataFrame or other). Using GroupBy and splitting using more than one key, perform some queries against that data. Explain what question you’re trying to answer and show the results/output. Come up with a total of three (3) different queries.

## Part One

**np.mean**: np.mean provides the mean of the value in question for the flattened array or for each category of a specified grouping - if the value is numeric.
    
**np.std**: np.std provides the standard deviation of the value in question for the flattened array or for each category of a specified grouping - if the value is numeric.

**np.var**: np.std provides the variance of the value in question for the flattened array or for each category of a specified grouping - if the value is numeric.

**np.argmin**: np.argmin returns the indices of the minimum values in the array, or in the rows or columns.

**np.argmax**: np.argmin returns the indices of the maximum values in the array, or in the rows or columns.

**np.median**: np.median returns the median for an np array or vector.

**np.percentile**: np.percentile returns the value of the specified percentile (e.g. 0, 25, 50 , 75, 100) for an array or vector.


## Part Two

In [23]:
import numpy as np

import matplotlib as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

arrayExample = np.array([[10, 7, 4], [3, 2, 1], [15,25,35],[100,101,102]])
arrayExample


array([[ 10,   7,   4],
       [  3,   2,   1],
       [ 15,  25,  35],
       [100, 101, 102]])

In [5]:
# return the mean for the entire array
np.mean(arrayExample)

33.75

In [7]:
#return the mean of the columns
np.mean(arrayExample, axis = 0)

array([32.  , 33.75, 35.5 ])

In [8]:
#return the mean of the rows
np.mean(arrayExample, axis = 1)

array([  7.,   2.,  25., 101.])

In [9]:
# return the indice of the maxium value in the array
np.argmax(arrayExample)

11

In [10]:
# return the indice of the maxium value in the array's columns
np.argmax(arrayExample, axis=0)

array([3, 3, 3], dtype=int64)

In [14]:
# return the indice of the minimum value in the array
np.argmin(arrayExample)

5

In [12]:
# return the value of the 25th percentile for the array
np.percentile(arrayExample, 25)

3.75

In [13]:
# return the value of the 95th percentile for the array
np.percentile(arrayExample, 95)

101.44999999999999

## Part Three

Find a sample data set (or create a reasonable data set and place in an appropriate structure, e.g., DataFrame or other). Using GroupBy and splitting using more than one key, perform some queries against that data. Explain what question you’re trying to answer and show the results/output. Come up with a total of three (3) different queries.

In [22]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20

dfZRental = pd.read_csv('Zillow_Rental_2014-2020.csv')
# melt te df so i can work on it
dfZRentalPivot = dfZRental.melt(id_vars=['RegionID','RegionName', 'SizeRank'], var_name='YYYY-MM-DD')

dfZRentalPivot['yr'] = pd.DatetimeIndex(dfZRentalPivot['YYYY-MM-DD']).year
dfZRentalPivot['period'] = pd.DatetimeIndex(dfZRentalPivot['YYYY-MM-DD']).month

# split region into city and state columns so i can group by state
dfZRentalPivot[['City','State']] = dfZRentalPivot.RegionName.str.split(", ",expand=True)

dfZRentalPivot.head(5)

RegionID                          RegionName  SizeRank YYYY-MM-DD   value  \
0    102001                       United States         0    2014-01  1349.0   
1    394913                        New York, NY         1    2014-01  2318.0   
2    753899  Los Angeles-Long Beach-Anaheim, CA         2    2014-01  1856.0   
3    394463                         Chicago, IL         3    2014-01  1533.0   
4    394514               Dallas-Fort Worth, TX         4    2014-01  1221.0   

     yr  period                            City State  
0  2014       1                   United States  None  
1  2014       1                        New York    NY  
2  2014       1  Los Angeles-Long Beach-Anaheim    CA  
3  2014       1                         Chicago    IL  
4  2014       1               Dallas-Fort Worth    TX

#### First Question: average rent (value column) 2014 - 2020 for each city

In [24]:

dfZRentalPivot.groupby(['State', 'City']).mean()


RegionID  SizeRank       value       yr  period
State City                                                           
AL    Birmingham      394388.0      49.0  1039.72500  2016.85     6.3
AR    Little Rock     394798.0      76.0   861.97500  2016.85     6.3
AZ    Phoenix         394976.0      14.0  1225.00000  2016.85     6.3
      Tucson          395167.0      53.0  1077.03750  2016.85     6.3
CA    Bakersfield     394357.0      63.0  1110.18750  2016.85     6.3
...                        ...       ...         ...      ...     ...
VA    Virginia Beach  395194.0      36.0  1266.18750  2016.85     6.3
WA    Seattle         395078.0      15.0  1729.12500  2016.85     6.3
      Spokane         395113.0      99.0  1004.35443  2016.85     6.3
WI    Madison         394816.0      87.0  1241.22500  2016.85     6.3
      Milwaukee       394862.0      39.0  1030.00000  2016.85     6.3

[105 rows x 5 columns]

#### Second Question: average rent (value column) for each state and city by year

In [26]:
dfZRentalPivot.groupby(['State', 'City', 'yr']).mean()

RegionID  SizeRank        value  period
State City       yr                                           
AL    Birmingham 2014  394388.0      49.0   971.916667     6.5
                 2015  394388.0      49.0   995.250000     6.5
                 2016  394388.0      49.0  1013.166667     6.5
                 2017  394388.0      49.0  1034.916667     6.5
                 2018  394388.0      49.0  1061.833333     6.5
...                         ...       ...          ...     ...
WI    Milwaukee  2016  394862.0      39.0  1016.083333     6.5
                 2017  394862.0      39.0  1031.250000     6.5
                 2018  394862.0      39.0  1051.250000     6.5
                 2019  394862.0      39.0  1077.833333     6.5
                 2020  394862.0      39.0  1098.000000     4.5

[735 rows x 4 columns]

#### Third Question: Max rent (value column) for each state by year

In [27]:
dfZRentalPivot.groupby(['State', 'yr']).max()

RegionID      RegionName  SizeRank YYYY-MM-DD   value  period  \
State yr                                                                    
AL    2014    394388  Birmingham, AL        49    2014-12   982.0      12   
      2015    394388  Birmingham, AL        49    2015-12  1005.0      12   
      2016    394388  Birmingham, AL        49    2016-12  1019.0      12   
      2017    394388  Birmingham, AL        49    2017-12  1048.0      12   
      2018    394388  Birmingham, AL        49    2018-12  1080.0      12   
...              ...             ...       ...        ...     ...     ...   
WI    2016    394862   Milwaukee, WI        87    2016-12  1236.0      12   
      2017    394862   Milwaukee, WI        87    2017-12  1261.0      12   
      2018    394862   Milwaukee, WI        87    2018-12  1291.0      12   
      2019    394862   Milwaukee, WI        87    2019-12  1320.0      12   
      2020    394862   Milwaukee, WI        87    2020-08  1340.0       8   

                  City  
State yr                
AL    2014  Birmingham  
      2015  Birmingham  
      2016  Birmingham  
      2017  Birmingham  
      2018  Birmingham  
...                ...  
WI    2016   Milwaukee  
      2017   Milwaukee  
      2018   Milwaukee  
      2019   Milwaukee  
      2020   Milwaukee  

[280 rows x 7 columns]